import {
  copyFileSync,
  existsSync,
  linkSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs'
import { spawnSync } from 'node:child_process'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import Ajv2020Module from 'ajv/dist/2020.js'
import { runLikeC4Cli } from '../src/adapters/likec4-cli.js'

const repositoryRoot = fileURLToPath(new URL('..', import.meta.url))
const Ajv2020 = Ajv2020Module.default

describe('YarraMate LikeC4 adapter CLI', () => {
  it('checks a complete adapter export without writing derived output', () => {
    const result = runLikeC4Cli(
      [
        'check',
        'test/fixtures/valid/governed-change.projection.yaml',
        'test/fixtures/valid/governed-change.likec4-mapping.yaml',
        'test/fixtures/valid/governed-change.workspace.yaml',
      ],
      repositoryRoot,
    )

    expect(result).toEqual({
      exitCode: 0,
      stdout: 'Checked LikeC4 export governed-change@1.0: no errors\n',
      stderr: '',
    })
  })

  it('emits schema-valid machine results for successful and failing checks', () => {
    const schema = JSON.parse(
      readFileSync(
        join(
          repositoryRoot,
          'schema/yarramate-likec4-check-result.schema.json',
        ),
        'utf8',
      ),
    )
    const adapterDiagnosticSchema = JSON.parse(
      readFileSync(
        join(
          repositoryRoot,
          'schema/yarramate-likec4-diagnostic-result.schema.json',
        ),
        'utf8',
      ),
    )
    const coreDiagnosticSchema = JSON.parse(
      readFileSync(
        join(
          repositoryRoot,
          'schema/yarramate-diagnostic-result.schema.json',
        ),
        'utf8',
      ),
    )
    const validate = new Ajv2020({ allErrors: true })
      .addSchema(coreDiagnosticSchema)
      .addSchema(adapterDiagnosticSchema)
      .compile(schema)
    const success = runLikeC4Cli(
      [
        'check',
        'test/fixtures/valid/governed-change.projection.yaml',
        'test/fixtures/valid/governed-change.likec4-mapping.yaml',
        '--json',
        'test/fixtures/valid/governed-change.workspace.yaml',
      ],
      repositoryRoot,
    )
    const failure = runLikeC4Cli(
      [
        'check',
        '.yarramate/projections/likec4-export-path.yaml',
        '.yarramate/integrations/likec4/subject-mapping.yaml',
        '--json',
        '.yarramate/workspace.yaml',
      ],
      repositoryRoot,
    )

    expect(JSON.parse(success.stdout)).toEqual({
      format: 'yarramate/likec4-check-result/v1',
      ok: true,
      diagnostics: [],
    })
    expect(JSON.parse(failure.stdout)).toMatchObject({
      format: 'yarramate/likec4-check-result/v1',
      ok: false,
      diagnostics: expect.arrayContaining([
        expect.objectContaining({ code: 'YMLC104' }),
      ]),
    })
    expect(validate(JSON.parse(success.stdout))).toBe(true)
    expect(
      validate(JSON.parse(failure.stdout)),
      JSON.stringify(validate.errors ?? []),
    ).toBe(true)
  })

  it('checks bundled kind compatibility without creating a project', () => {
    const result = runLikeC4Cli(
      [
        'check',
        '.yarramate/projections/likec4-export-path.yaml',
        '.yarramate/integrations/likec4/subject-mapping.yaml',
        '.yarramate/workspace.yaml',
      ],
      repositoryRoot,
    )

    expect(result.exitCode).toBe(1)
    expect(JSON.parse(result.stdout)).toMatchObject({
      diagnostics: expect.arrayContaining([
        expect.objectContaining({
          code: 'YMLC104',
          subject: 'yarramate-repository#likec4-export-source',
        }),
      ]),
    })
  })

  it('exports a native workspace projection to LikeC4 source', () => {
    const result = runLikeC4Cli(
      [
        'export',
        'test/fixtures/valid/governed-change.projection.yaml',
        'test/fixtures/valid/governed-change.likec4-mapping.yaml',
        'test/fixtures/valid/governed-change.workspace.yaml',
      ],
      repositoryRoot,
    )

    expect(result.exitCode).toBe(0)
    expect(result.stderr).toBe('')
    expect(result.stdout).toContain(
      '// Generated by YarraMate. Edit the native documents, not this file.',
    )
    expect(result.stdout).toContain(
      "controlPlane = applicationComponent 'Control plane'",
    )
    expect(result.stdout).toContain(
      "controlPlane -[assignment]-> edgeRuntime 'deployed on'",
    )
  })

  it('exports a state comparison without moving presentation into Core', () => {
    const parent = mkdtempSync(join(tmpdir(), 'yarramate-likec4-compare-'))
    try {
      writeFileSync(
        join(parent, 'architecture.yaml'),
        `format: yarramate/v1
id: system
profile: yarramate/core@0.1
states:
  - id: baseline
    kind: baseline
    name: Baseline
  - id: target
    kind: target
    name: Target
concepts:
  - id: legacy
    kind: applicationComponent
    name: Legacy
    presentIn: [baseline]
  - id: modern
    kind: applicationComponent
    name: Modern
    presentIn: [target]
relationships: []
`,
      )
      writeFileSync(
        join(parent, 'comparison.projection.yaml'),
        `format: yarramate/projection/v1
id: system-change
version: "1.0"
query:
  states: [system#baseline, system#target]
`,
      )
      writeFileSync(
        join(parent, 'likec4.mapping.yaml'),
        `format: yarramate/adapter-mapping/v1
id: system-likec4
version: "1.0"
adapter: likec4
mappings:
  - native: system#legacy
    external: legacy
    type: concept
  - native: system#modern
    external: modern
    type: concept
`,
      )

      const result = runLikeC4Cli(
        [
          'export',
          'comparison.projection.yaml',
          'likec4.mapping.yaml',
          '--compare',
          'system#baseline',
          'system#target',
          'architecture.yaml',
        ],
        parent,
      )

      expect(result.exitCode).toBe(0)
      expect(result.stderr).toBe('')
      expect(result.stdout).toContain(`yarramateChange 'removed'`)
      expect(result.stdout).toContain(`yarramateChange 'added'`)
      writeFileSync(join(parent, 'model.likec4'), result.stdout)
      copyFileSync(
        join(repositoryRoot, '.yarramate/integrations/likec4/prototype/specification.likec4'),
        join(parent, 'specification.likec4'),
      )
      writeFileSync(
        join(parent, 'likec4.config.json'),
        JSON.stringify({
          $schema: 'https://likec4.dev/schemas/config.json',
          name: 'state-comparison',
        }),
      )
      const validation = spawnSync(
        join(repositoryRoot, 'node_modules/.bin/likec4'),
        [
          'validate',
          '--json',
          '--no-layout',
          '--file',
          'model.likec4',
          '.',
        ],
        { cwd: parent, encoding: 'utf8' },
      )
      expect(
        validation.status,
        `${validation.stderr}\n${validation.stdout}`,
      ).toBe(0)
      expect(JSON.parse(validation.stdout)).toMatchObject({
        valid: true,
        errors: [],
        stats: { totalErrors: 0 },
      })
      const project = join(parent, 'generated')
      const materialized = runLikeC4Cli(
        [
          'export-project',
          'comparison.projection.yaml',
          'likec4.mapping.yaml',
          project,
          '--compare',
          'system#baseline',
          'system#target',
          'architecture.yaml',
        ],
        parent,
      )
      expect(materialized.exitCode).toBe(0)
      expect(
        JSON.parse(
          readFileSync(
            join(project, 'yarramate.generated.json'),
            'utf8',
          ),
        ),
      ).toMatchObject({
        comparison: {
          from: 'system#baseline',
          to: 'system#target',
        },
      })
      const conflicting = runLikeC4Cli(
        [
          'export-project',
          'comparison.projection.yaml',
          'likec4.mapping.yaml',
          project,
          '--compare',
          'system#target',
          'system#baseline',
          'architecture.yaml',
        ],
        parent,
      )
      expect(conflicting).toEqual({
        exitCode: 2,
        stdout: '',
        stderr: `Output directory already exists: ${project}\n`,
      })
    } finally {
      rmSync(parent, { recursive: true, force: true })
    }
  })

  it('emits schema-valid diagnostics for adapter command failures', () => {
    const schema = JSON.parse(
      readFileSync(
        `${repositoryRoot}/schema/yarramate-likec4-diagnostic-result.schema.json`,
        'utf8',
      ),
    )
    const diagnosticSchema = JSON.parse(
      readFileSync(
        `${repositoryRoot}/schema/yarramate-diagnostic-result.schema.json`,
        'utf8',
      ),
    )
    const validate = new Ajv2020({ allErrors: true })
      .addSchema(diagnosticSchema)
      .compile(schema)
    const result = runLikeC4Cli(
      [
        'export',
        'test/fixtures/valid/governed-change.projection.yaml',
        'test/fixtures/invalid/adapter-mapping-missing-adapter.yaml',
        'test/fixtures/valid/governed-change.workspace.yaml',
      ],
      repositoryRoot,
    )

    expect(result.exitCode).toBe(1)
    expect(
      validate(JSON.parse(result.stdout)),
      JSON.stringify(validate.errors ?? []),
    ).toBe(true)
  })

  it('produces source whose generated project resolves profile kinds', () => {
    const result = runLikeC4Cli(
      [
        'export',
        'test/fixtures/valid/governed-change.projection.yaml',
        'test/fixtures/valid/governed-change.likec4-mapping.yaml',
        'test/fixtures/valid/governed-change.workspace.yaml',
      ],
      repositoryRoot,
    )
    expect(result.exitCode).toBe(0)
    const fixtureRoot = mkdtempSync(
      join(tmpdir(), 'yarramate-likec4-validation-'),
    )
    try {
      writeFileSync(join(fixtureRoot, 'model.likec4'), result.stdout)
      copyFileSync(
        join(repositoryRoot, '.yarramate/integrations/likec4/prototype/specification.likec4'),
        join(fixtureRoot, 'specification.likec4'),
      )
      writeFileSync(
        join(fixtureRoot, 'likec4.config.json'),
        JSON.stringify({
          $schema: 'https://likec4.dev/schemas/config.json',
          name: 'yarramate-generated-validation',
        }),
      )
      const validation = spawnSync(
        join(repositoryRoot, 'node_modules/.bin/likec4'),
        [
          'validate',
          '--json',
          '--no-layout',
          '--file',
          'model.likec4',
          '.',
        ],
        { cwd: fixtureRoot, encoding: 'utf8' },
      )

      expect(
        validation.status,
        `${validation.stderr}\n${validation.stdout}`,
      ).toBe(0)
      expect(JSON.parse(validation.stdout)).toMatchObject({
        valid: true,
        errors: [],
        stats: { totalErrors: 0 },
      })
    } finally {
      rmSync(fixtureRoot, { recursive: true, force: true })
    }
  })

  it('materializes a self-contained project without merging projections', () => {
    const parent = mkdtempSync(join(tmpdir(), 'yarramate-likec4-project-'))
    const project = join(parent, 'governed-change')
    try {
      const result = runLikeC4Cli(
        [
          'export-project',
          'test/fixtures/valid/governed-change.projection.yaml',
          'test/fixtures/valid/governed-change.likec4-mapping.yaml',
          project,
          'test/fixtures/valid/governed-change.workspace.yaml',
        ],
        repositoryRoot,
      )

      expect(result).toEqual({
        exitCode: 0,
        stdout: `Wrote LikeC4 project to ${project}\n`,
        stderr: '',
      })
      expect(readFileSync(join(project, 'model.likec4'), 'utf8')).toContain(
        "controlPlane = applicationComponent 'Control plane'",
      )
      expect(
        JSON.parse(
          readFileSync(join(project, 'likec4.config.json'), 'utf8'),
        ),
      ).toMatchObject({
        name: 'yarramate-governed-change-1-0',
      })
      expect(
        readFileSync(join(project, 'specification.likec4'), 'utf8'),
      ).toContain('element driver')
      const marker = JSON.parse(
        readFileSync(
          join(project, 'yarramate.generated.json'),
          'utf8',
        ),
      )
      expect(marker).toMatchObject({
        format: 'yarramate/likec4-generated-project/v1',
        projection: 'governed-change@1.0',
        mapping: 'governed-change-likec4@1.0',
        files: [
          'likec4.config.json',
          'model.likec4',
          'specification.likec4',
        ],
      })
      expect(marker.digests).toEqual({
        'likec4.config.json': expect.stringMatching(/^[a-f0-9]{64}$/),
        'model.likec4': expect.stringMatching(/^[a-f0-9]{64}$/),
        'specification.likec4': expect.stringMatching(/^[a-f0-9]{64}$/),
      })
      const markerSchema = JSON.parse(
        readFileSync(
          join(
            repositoryRoot,
            'schema/yarramate-likec4-generated-project.schema.json',
          ),
          'utf8',
        ),
      )
      const validateMarker = new Ajv2020({ allErrors: true }).compile(
        markerSchema,
      )
      expect(
        validateMarker(marker),
        JSON.stringify(validateMarker.errors ?? []),
      ).toBe(true)

      const validation = spawnSync(
        join(repositoryRoot, 'node_modules/.bin/likec4'),
        ['validate', '--json', '--no-layout', project],
        { cwd: repositoryRoot, encoding: 'utf8' },
      )
      expect(
        validation.status,
        `${validation.stderr}\n${validation.stdout}`,
      ).toBe(0)
      expect(JSON.parse(validation.stdout)).toMatchObject({
        valid: true,
        errors: [],
      })
    } finally {
      rmSync(parent, { recursive: true, force: true })
    }
  })

  it('materializes one project with multiple projection views', () => {
    const parent = mkdtempSync(join(tmpdir(), 'yarramate-likec4-model-'))
    const project = join(parent, 'generated')
    try {
      writeFileSync(
        join(parent, 'architecture.yaml'),
        `format: yarramate/v1
id: system
profile: yarramate/core@0.1
states:
  - id: baseline
    kind: baseline
    name: Baseline
  - id: target
    kind: target
    name: Target
concepts:
  - id: shared
    kind: applicationComponent
    name: Shared
  - id: legacy
    kind: applicationComponent
    name: Legacy
    presentIn: [baseline]
  - id: modern
    kind: applicationComponent
    name: Modern
    presentIn: [target]
relationships:
  - id: legacy-uses-shared
    kind: association
    from: legacy
    to: shared
    presentIn: [baseline]
  - id: modern-uses-shared
    kind: association
    from: modern
    to: shared
    presentIn: [target]
`,
      )
      writeFileSync(
        join(parent, 'baseline.projection.yaml'),
        `format: yarramate/projection/v1
id: baseline
version: "1.0"
query:
  states: [system#baseline]
`,
      )
      writeFileSync(
        join(parent, 'target.projection.yaml'),
        `format: yarramate/projection/v1
id: target
version: "1.0"
query:
  states: [system#target]
`,
      )
      writeFileSync(
        join(parent, 'empty.projection.yaml'),
        `format: yarramate/projection/v1
id: empty
version: "1.0"
query:
  kinds: [yarramate/core@0.1#device]
  relationships: connected
`,
      )
      writeFileSync(
        join(parent, 'likec4.mapping.yaml'),
        `format: yarramate/adapter-mapping/v1
id: system-likec4
version: "1.0"
adapter: likec4
mappings:
  - native: system#legacy
    external: legacy
    type: concept
  - native: system#modern
    external: modern
    type: concept
  - native: system#shared
    external: shared
    type: concept
`,
      )
      writeFileSync(
        join(parent, 'yarramate.likec4.yaml'),
        `format: yarramate/likec4-project/v1
id: system
version: "1.0"
title: System architecture
mapping: likec4.mapping.yaml
views:
  - id: index
    projection: baseline.projection.yaml
  - projection: target.projection.yaml
  - projection: empty.projection.yaml
`,
      )

      const checked = runLikeC4Cli(
        [
          'check',
          'yarramate.likec4.yaml',
          '--json',
          'architecture.yaml',
        ],
        parent,
      )
      expect(checked).toEqual({
        exitCode: 0,
        stdout: `${JSON.stringify(
          {
            format: 'yarramate/likec4-check-result/v1',
            ok: true,
            diagnostics: [],
          },
          null,
          2,
        )}\n`,
        stderr: '',
      })

      const args = [
        'export-project',
        'yarramate.likec4.yaml',
        project,
        'architecture.yaml',
      ]
      const result = runLikeC4Cli(args, parent)

      expect(result).toEqual({
        exitCode: 0,
        stdout: `Wrote LikeC4 project to ${project}\n`,
        stderr: '',
      })
      const model = readFileSync(join(project, 'model.likec4'), 'utf8')
      expect(model.match(/^model \{/gm)).toHaveLength(1)
      expect(model.match(/^views \{/gm)).toHaveLength(1)
      expect(model).toContain('view index')
      expect(model).not.toContain('view baseline')
      expect(model).toContain('view target')
      expect(model).toContain('view empty')
      expect(model).toContain("legacy = applicationComponent 'Legacy'")
      expect(model).toContain("modern = applicationComponent 'Modern'")
      expect(model).toContain("shared = applicationComponent 'Shared'")
      expect(model).toContain(
        'view index {\n    include legacy, shared\n',
      )
      expect(model).toContain(
        'view target {\n    include modern, shared\n',
      )
      expect(model).not.toContain(
        'view index {\n    include *\n',
      )
      expect(model).not.toContain(
        'view target {\n    include *\n',
      )
      expect(model).toContain(
        "view empty {\n    include * where metadata.yarramateId is '__yarramate_no_match__'\n",
      )
      const baselineView = model.slice(
        model.indexOf('  view index {'),
        model.indexOf('  view target {'),
      )
      const targetView = model.slice(
        model.indexOf('  view target {'),
        model.indexOf('  view empty {'),
      )
      expect(baselineView).toContain('    exclude * -> *')
      expect(baselineView).toContain(
        "metadata.yarramateId is 'system#legacy-uses-shared'",
      )
      expect(baselineView).not.toContain(
        "metadata.yarramateId is 'system#modern-uses-shared'",
      )
      expect(targetView).toContain('    exclude * -> *')
      expect(targetView).toContain(
        "metadata.yarramateId is 'system#modern-uses-shared'",
      )
      expect(targetView).not.toContain(
        "metadata.yarramateId is 'system#legacy-uses-shared'",
      )
      expect(
        JSON.parse(
          readFileSync(join(project, 'likec4.config.json'), 'utf8'),
        ),
      ).toMatchObject({
        name: 'yarramate-system-1-0',
        title: 'System architecture',
      })
      const marker = JSON.parse(
        readFileSync(
          join(project, 'yarramate.generated.json'),
          'utf8',
        ),
      )
      expect(marker).toMatchObject({
        format: 'yarramate/likec4-generated-project/v2',
        project: 'system@1.0',
        mapping: 'system-likec4@1.0',
        views: [
          { id: 'index', projection: 'baseline@1.0' },
          { projection: 'target@1.0' },
          { projection: 'empty@1.0' },
        ],
      })
      const markerSchema = JSON.parse(
        readFileSync(
          join(
            repositoryRoot,
            'schema/yarramate-likec4-generated-project-v2.schema.json',
          ),
          'utf8',
        ),
      )
      const validateMarker = new Ajv2020({ allErrors: true }).compile(
        markerSchema,
      )
      expect(
        validateMarker(marker),
        JSON.stringify(validateMarker.errors ?? []),
      ).toBe(true)

      const validation = spawnSync(
        join(repositoryRoot, 'node_modules/.bin/likec4'),
        [
          'validate',
          '--json',
          '--no-layout',
          '--file',
          'model.likec4',
          '.',
        ],
        { cwd: project, encoding: 'utf8' },
      )
      expect(
        validation.status,
        `${validation.stderr}\n${validation.stdout}`,
      ).toBe(0)
      expect(JSON.parse(validation.stdout)).toMatchObject({
        valid: true,
        errors: [],
        stats: {
          filteredErrors: 0,
          totalErrors: 0,
        },
      })
      expect(runLikeC4Cli(args, parent)).toEqual({
        exitCode: 0,
        stdout: `Updated LikeC4 project at ${project}\n`,
        stderr: '',
      })
    } finally {
      rmSync(parent, { recursive: true, force: true })
    }
  })

  it('materializes the repository starter pack as independent views', () => {
    const parent = mkdtempSync(
      join(tmpdir(), 'yarramate-likec4-starter-pack-'),
    )
    const project = join(parent, 'generated')
    try {
      const result = runLikeC4Cli(
        [
          'export-project',
          '.yarramate/integrations/likec4/project.yaml',
          project,
          '.yarramate/workspace.yaml',
        ],
        repositoryRoot,
      )

      expect(result.exitCode).toBe(0)
      const model = readFileSync(join(project, 'model.likec4'), 'utf8')
      expect(model.match(/^  view /gm)).toHaveLength(14)
      expect(model).not.toMatch(/^    include \*$/gm)
      expect(model).toContain('view index')
      expect(model).not.toContain('view starter-landscape')
      expect(model).toContain('view starter-motivation')
      expect(model).toContain('view starter-strategy')
      expect(model).toContain('view product-journeys')
      expect(model).toContain('view starter-business-operation')
      expect(model).toContain('view starter-application-cooperation')
      expect(model).toContain('view starter-information-structure')
      expect(model).toContain('view starter-technology-deployment')
      expect(model).toContain('view starter-implementation-roadmap')
      expect(model).toContain('view engine-components')
      expect(model).toContain(
        "view starter-technology-deployment {\n" +
          "    title 'Technology and deployment'\n" +
          "    description 'Technology structure, behavior, services, networks, and deployed artifacts.'\n" +
          '    include consumerPackage, packageConsumerTests, productDesignSolutionBeforeBuild, productDiscoverProjectArchitecture, productStableCli',
      )
      const marker = JSON.parse(
        readFileSync(
          join(project, 'yarramate.generated.json'),
          'utf8',
        ),
      )
      expect(marker.views).toHaveLength(14)
      expect(marker.views[0]).toEqual({
        id: 'index',
        projection: 'starter-landscape@1.0',
      })
      expect(marker.views.filter(({ projection }: {
        projection: string
      }) => projection.startsWith('starter-')).map(({ projection }: {
        projection: string
      }) => projection)).toEqual([
        'starter-landscape@1.0',
        'starter-motivation@1.0',
        'starter-strategy@1.0',
        'starter-business-operation@1.0',
        'starter-application-cooperation@1.0',
        'starter-information-structure@1.0',
        'starter-technology-deployment@1.0',
        'starter-implementation-roadmap@1.0',
      ])
    } finally {
      rmSync(parent, { recursive: true, force: true })
    }
  })

  it('rejects duplicate rendered view identities in a project definition', () => {
    const parent = mkdtempSync(
      join(tmpdir(), 'yarramate-likec4-duplicate-view-'),
    )
    const definition = join(parent, 'project.yaml')
    try {
      writeFileSync(
        definition,
        `format: yarramate/likec4-project/v1
id: duplicate-view
version: "1.0"
title: Duplicate view
mapping: test/fixtures/valid/governed-change.likec4-mapping.yaml
views:
  - id: index
    projection: test/fixtures/valid/governed-change.projection.yaml
  - id: index
    projection: test/fixtures/valid/governed-change.projection.yaml
`,
      )

      const result = runLikeC4Cli(
        [
          'check',
          definition,
          '--json',
          'test/fixtures/valid/governed-change.workspace.yaml',
        ],
        repositoryRoot,
      )

      expect(result.exitCode).toBe(1)
      expect(JSON.parse(result.stdout)).toMatchObject({
        ok: false,
        diagnostics: [
          {
            severity: 'error',
            code: 'YMLC107',
            message: 'LikeC4 view identity "index" is duplicated',
            path: definition,
            pointer: '/views/1/id',
            line: 9,
            column: 9,
          },
        ],
      })
    } finally {
      rmSync(parent, { recursive: true, force: true })
    }
  })

  it('safely regenerates a project carrying its matching marker', () => {
    const parent = mkdtempSync(join(tmpdir(), 'yarramate-likec4-update-'))
    const project = join(parent, 'governed-change')
    const args = [
      'export-project',
      'test/fixtures/valid/governed-change.projection.yaml',
      'test/fixtures/valid/governed-change.likec4-mapping.yaml',
      project,
      'test/fixtures/valid/governed-change.workspace.yaml',
    ]
    try {
      expect(runLikeC4Cli(args, repositoryRoot).exitCode).toBe(0)
      writeFileSync(join(project, 'review-notes.md'), 'preserve me\n')

      const result = runLikeC4Cli(args, repositoryRoot)

      expect(result).toEqual({
        exitCode: 0,
        stdout: `Updated LikeC4 project at ${project}\n`,
        stderr: '',
      })
      expect(readFileSync(join(project, 'review-notes.md'), 'utf8')).toBe(
        'preserve me\n',
      )
    } finally {
      rmSync(parent, { recursive: true, force: true })
    }
  })

  it('atomically replaces each owned file during regeneration', () => {
    const parent = mkdtempSync(
      join(tmpdir(), 'yarramate-likec4-atomic-update-'),
    )
    const project = join(parent, 'generated')
    const document = join(parent, 'system.yaml')
    const projection = join(parent, 'system.projection.yaml')
    const mapping = join(parent, 'system.mapping.yaml')
    const args = [
      'export-project',
      projection,
      mapping,
      project,
      document,
    ]
    const writeDocument = (name: string) =>
      writeFileSync(
        document,
        `format: yarramate/v1
id: system
profile: yarramate/core@0.1
concepts:
  - id: service
    kind: applicationComponent
    name: ${name}
relationships: []
`,
      )
    try {
      writeDocument('Original service')
      writeFileSync(
        projection,
        `format: yarramate/projection/v1
id: system
version: "1.0"
query: {}
`,
      )
      writeFileSync(
        mapping,
        `format: yarramate/adapter-mapping/v1
id: system-likec4
version: "1.0"
adapter: likec4
mappings:
  - native: system#service
    external: service
    type: concept
`,
      )
      expect(runLikeC4Cli(args, repositoryRoot).exitCode).toBe(0)
      const model = join(project, 'model.likec4')
      const priorModel = join(parent, 'prior-model.likec4')
      linkSync(model, priorModel)
      writeDocument('Updated service')

      expect(runLikeC4Cli(args, repositoryRoot).exitCode).toBe(0)

      expect(readFileSync(model, 'utf8')).toContain(
        "service = applicationComponent 'Updated service'",
      )
      expect(readFileSync(priorModel, 'utf8')).toContain(
        "service = applicationComponent 'Original service'",
      )
    } finally {
      rmSync(parent, { recursive: true, force: true })
    }
  })

  it('refuses to overwrite a generated file changed since the marker', () => {
    const parent = mkdtempSync(
      join(tmpdir(), 'yarramate-likec4-drift-'),
    )
    const project = join(parent, 'governed-change')
    const args = [
      'export-project',
      'test/fixtures/valid/governed-change.projection.yaml',
      'test/fixtures/valid/governed-change.likec4-mapping.yaml',
      project,
      'test/fixtures/valid/governed-change.workspace.yaml',
    ]
    try {
      expect(runLikeC4Cli(args, repositoryRoot).exitCode).toBe(0)
      const modelPath = join(project, 'model.likec4')
      writeFileSync(modelPath, `${readFileSync(modelPath, 'utf8')}// edited\n`)

      const result = runLikeC4Cli(args, repositoryRoot)

      expect(result).toEqual({
        exitCode: 2,
        stdout: '',
        stderr: `Generated project file has changed: ${modelPath}\n`,
      })
    } finally {
      rmSync(parent, { recursive: true, force: true })
    }
  })

  it('refuses regeneration when the ownership marker is malformed', () => {
    const parent = mkdtempSync(
      join(tmpdir(), 'yarramate-likec4-malformed-marker-'),
    )
    const project = join(parent, 'governed-change')
    const args = [
      'export-project',
      'test/fixtures/valid/governed-change.projection.yaml',
      'test/fixtures/valid/governed-change.likec4-mapping.yaml',
      project,
      'test/fixtures/valid/governed-change.workspace.yaml',
    ]
    try {
      expect(runLikeC4Cli(args, repositoryRoot).exitCode).toBe(0)
      writeFileSync(
        join(project, 'yarramate.generated.json'),
        JSON.stringify({
          format: 'yarramate/likec4-generated-project/v1',
          projection: 'governed-change@1.0',
          mapping: 'governed-change-likec4@1.0',
          files: [],
        }),
      )

      const result = runLikeC4Cli(args, repositoryRoot)

      expect(result).toEqual({
        exitCode: 2,
        stdout: '',
        stderr: `Output directory already exists: ${project}\n`,
      })
    } finally {
      rmSync(parent, { recursive: true, force: true })
    }
  })

  it('refuses regeneration through a symlinked generated file', () => {
    const parent = mkdtempSync(
      join(tmpdir(), 'yarramate-likec4-symlink-'),
    )
    const project = join(parent, 'governed-change')
    const outside = join(parent, 'outside.likec4')
    const args = [
      'export-project',
      'test/fixtures/valid/governed-change.projection.yaml',
      'test/fixtures/valid/governed-change.likec4-mapping.yaml',
      project,
      'test/fixtures/valid/governed-change.workspace.yaml',
    ]
    try {
      expect(runLikeC4Cli(args, repositoryRoot).exitCode).toBe(0)
      writeFileSync(outside, 'do not replace\n')
      rmSync(join(project, 'model.likec4'))
      symlinkSync(outside, join(project, 'model.likec4'))

      const result = runLikeC4Cli(args, repositoryRoot)

      expect(result).toEqual({
        exitCode: 2,
        stdout: '',
        stderr: `Generated project contains an unsafe file: ${join(project, 'model.likec4')}\n`,
      })
      expect(readFileSync(outside, 'utf8')).toBe('do not replace\n')
    } finally {
      rmSync(parent, { recursive: true, force: true })
    }
  })

  it('refuses to overwrite an existing project directory', () => {
    const project = mkdtempSync(
      join(tmpdir(), 'yarramate-likec4-existing-'),
    )
    try {
      const result = runLikeC4Cli(
        [
          'export-project',
          'test/fixtures/valid/governed-change.projection.yaml',
          'test/fixtures/valid/governed-change.likec4-mapping.yaml',
          project,
          'test/fixtures/valid/governed-change.workspace.yaml',
        ],
        repositoryRoot,
      )

      expect(result).toEqual({
        exitCode: 2,
        stdout: '',
        stderr: `Output directory already exists: ${project}\n`,
      })
    } finally {
      rmSync(project, { recursive: true, force: true })
    }
  })

  it('materializes extension kinds through an explicit kind mapping', () => {
    const parent = mkdtempSync(
      join(tmpdir(), 'yarramate-likec4-profiled-'),
    )
    const project = join(parent, 'export-path')
    try {
      const result = runLikeC4Cli(
        [
          'export-project',
          '.yarramate/projections/likec4-export-path.yaml',
          '.yarramate/integrations/likec4/subject-mapping.yaml',
          project,
          '--kinds',
          '.yarramate/integrations/likec4/kind-mapping.yaml',
          '.yarramate/workspace.yaml',
        ],
        repositoryRoot,
      )

      expect(result.exitCode).toBe(0)
      const model = readFileSync(join(project, 'model.likec4'), 'utf8')
      expect(model).toContain(
        "likec4ExportSource = artifact 'src/adapters/likec4-export.ts'",
      )
      expect(model).toContain(
        "yarramateKind 'yarramate/development@1.0#repository-file'",
      )
      expect(
        JSON.parse(
          readFileSync(
            join(project, 'yarramate.generated.json'),
            'utf8',
          ),
        ),
      ).toMatchObject({
        kindMapping: 'yarramate-development-likec4@1.0',
      })
    } finally {
      rmSync(parent, { recursive: true, force: true })
    }
  })

  it('rejects extension kinds not supported by the bundled specification before writing', () => {
    const parent = mkdtempSync(
      join(tmpdir(), 'yarramate-likec4-unsupported-'),
    )
    const project = join(parent, 'export-path')
    try {
      const result = runLikeC4Cli(
        [
          'export-project',
          '.yarramate/projections/likec4-export-path.yaml',
          '.yarramate/integrations/likec4/subject-mapping.yaml',
          project,
          '.yarramate/workspace.yaml',
        ],
        repositoryRoot,
      )

      expect(result.exitCode).toBe(1)
      expect(result.stderr).toBe('')
      expect(JSON.parse(result.stdout)).toEqual({
        format: 'yarramate/likec4-diagnostic-result/v1',
        diagnostics: [
          {
            severity: 'error',
            code: 'YMLC104',
            message:
              'Semantic concept kind "yarramate/development@1.0#repository-file" resolves to unsupported bundled LikeC4 kind "repository-file"',
            subject: 'yarramate-repository#likec4-export-source',
            path: '.yarramate/architecture/repository.yaml',
            pointer: '/concepts/15/kind',
            line: 70,
            column: 11,
          },
          {
            severity: 'error',
            code: 'YMLC104',
            message:
              'Semantic concept kind "yarramate/development@1.0#repository-file" resolves to unsupported bundled LikeC4 kind "repository-file"',
            subject: 'yarramate-repository#likec4-prepare-source',
            path: '.yarramate/architecture/repository.yaml',
            pointer: '/concepts/18/kind',
            line: 82,
            column: 11,
          },
          {
            severity: 'error',
            code: 'YMLC104',
            message:
              'Semantic concept kind "yarramate/development@1.0#repository-file" resolves to unsupported bundled LikeC4 kind "repository-file"',
            subject: 'yarramate-repository#likec4-project-source',
            path: '.yarramate/architecture/repository.yaml',
            pointer: '/concepts/19/kind',
            line: 86,
            column: 11,
          },
          {
            severity: 'error',
            code: 'YMLC104',
            message:
              'Semantic concept kind "yarramate/development@1.0#repository-file" resolves to unsupported bundled LikeC4 kind "repository-file"',
            subject:
              'yarramate-repository#likec4-project-definition-source',
            path: '.yarramate/architecture/repository.yaml',
            pointer: '/concepts/20/kind',
            line: 90,
            column: 11,
          },
          {
            severity: 'error',
            code: 'YMLC104',
            message:
              'Semantic concept kind "yarramate/development@1.0#repository-file" resolves to unsupported bundled LikeC4 kind "repository-file"',
            subject:
              'yarramate-repository#likec4-project-schema-source',
            path: '.yarramate/architecture/repository.yaml',
            pointer: '/concepts/45/kind',
            line: 195,
            column: 11,
          },
          {
            severity: 'error',
            code: 'YMLC104',
            message:
              'Semantic concept kind "yarramate/development@1.0#repository-file" resolves to unsupported bundled LikeC4 kind "repository-file"',
            subject:
              'yarramate-repository#likec4-generated-project-v2-schema-source',
            path: '.yarramate/architecture/repository.yaml',
            pointer: '/concepts/46/kind',
            line: 199,
            column: 11,
          },
        ],
      })
      expect(existsSync(project)).toBe(false)
    } finally {
      rmSync(parent, { recursive: true, force: true })
    }
  })

  it('rejects kind mappings targeting undeclared bundled kinds', () => {
    const parent = mkdtempSync(
      join(tmpdir(), 'yarramate-likec4-unknown-kind-'),
    )
    const project = join(parent, 'export-path')
    const kinds = join(parent, 'kinds.yaml')
    writeFileSync(
      kinds,
      `format: yarramate/likec4-kind-mapping/v1
id: unsupported-target
version: "1.0"
conceptKinds:
  - native: yarramate/development@1.0#repository-file
    external: customBox
relationshipKinds: []
`,
    )
    try {
      const result = runLikeC4Cli(
        [
          'export-project',
          '.yarramate/projections/likec4-export-path.yaml',
          '.yarramate/integrations/likec4/subject-mapping.yaml',
          project,
          '--kinds',
          kinds,
          '.yarramate/workspace.yaml',
        ],
        repositoryRoot,
      )

      expect(result.exitCode).toBe(1)
      expect(JSON.parse(result.stdout)).toMatchObject({
        diagnostics: expect.arrayContaining([
          expect.objectContaining({
            code: 'YMLC104',
            message:
              'Semantic concept kind "yarramate/development@1.0#repository-file" resolves to unsupported bundled LikeC4 kind "customBox"',
          }),
        ]),
      })
      expect(existsSync(project)).toBe(false)
    } finally {
      rmSync(parent, { recursive: true, force: true })
    }
  })
})
