import {
  copyFileSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { spawnSync } from 'node:child_process'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import Ajv2020Module from 'ajv/dist/2020.js'
import { runLikeC4Cli } from '../src/adapters/likec4-cli.js'

const repositoryRoot = fileURLToPath(new URL('..', import.meta.url))
const Ajv2020 = Ajv2020Module.default

describe('YarraMate LikeC4 adapter CLI', () => {
  it('exports a native workspace projection to LikeC4 source', () => {
    const result = runLikeC4Cli(
      [
        'export',
        'examples/governed-change/all.projection.yaml',
        'examples/governed-change/likec4.mapping.yaml',
        'examples/governed-change/yarramate.workspace.yaml',
      ],
      repositoryRoot,
    )

    expect(result.exitCode).toBe(0)
    expect(result.stderr).toBe('')
    expect(result.stdout).toContain(
      '// Generated by YarraMate. Edit the native documents, not this file.',
    )
    expect(result.stdout).toContain(
      "controlPlane = applicationComponent 'Control plane'",
    )
    expect(result.stdout).toContain(
      "controlPlane -[assignment]-> edgeRuntime 'deployed on'",
    )
    expect(result.stdout).not.toBe(
      readFileSync(
        `${repositoryRoot}/examples/governed-change/model.likec4`,
        'utf8',
      ),
    )
  })

  it('emits schema-valid diagnostics for adapter command failures', () => {
    const schema = JSON.parse(
      readFileSync(
        `${repositoryRoot}/schema/yarramate-likec4-diagnostic-result.schema.json`,
        'utf8',
      ),
    )
    const diagnosticSchema = JSON.parse(
      readFileSync(
        `${repositoryRoot}/schema/yarramate-diagnostic-result.schema.json`,
        'utf8',
      ),
    )
    const validate = new Ajv2020({ allErrors: true })
      .addSchema(diagnosticSchema)
      .compile(schema)
    const result = runLikeC4Cli(
      [
        'export',
        'examples/governed-change/all.projection.yaml',
        'test/fixtures/invalid/adapter-mapping-missing-adapter.yaml',
        'examples/governed-change/yarramate.workspace.yaml',
      ],
      repositoryRoot,
    )

    expect(result.exitCode).toBe(1)
    expect(
      validate(JSON.parse(result.stdout)),
      JSON.stringify(validate.errors ?? []),
    ).toBe(true)
  })

  it('produces source whose generated project resolves profile kinds', () => {
    const result = runLikeC4Cli(
      [
        'export',
        'examples/governed-change/all.projection.yaml',
        'examples/governed-change/likec4.mapping.yaml',
        'examples/governed-change/yarramate.workspace.yaml',
      ],
      repositoryRoot,
    )
    expect(result.exitCode).toBe(0)
    const fixtureRoot = mkdtempSync(
      join(tmpdir(), 'yarramate-likec4-validation-'),
    )
    try {
      writeFileSync(join(fixtureRoot, 'model.likec4'), result.stdout)
      copyFileSync(
        join(repositoryRoot, 'profile/specification.likec4'),
        join(fixtureRoot, 'specification.likec4'),
      )
      writeFileSync(
        join(fixtureRoot, 'likec4.config.json'),
        JSON.stringify({
          $schema: 'https://likec4.dev/schemas/config.json',
          name: 'yarramate-generated-validation',
        }),
      )
      const validation = spawnSync(
        join(repositoryRoot, 'node_modules/.bin/likec4'),
        [
          'validate',
          '--json',
          '--no-layout',
          '--file',
          'model.likec4',
          '.',
        ],
        { cwd: fixtureRoot, encoding: 'utf8' },
      )

      expect(
        validation.status,
        `${validation.stderr}\n${validation.stdout}`,
      ).toBe(0)
      expect(JSON.parse(validation.stdout)).toMatchObject({
        valid: true,
        errors: [],
        stats: { totalErrors: 0 },
      })
    } finally {
      rmSync(fixtureRoot, { recursive: true, force: true })
    }
  })

  it('materializes a self-contained project without merging projections', () => {
    const parent = mkdtempSync(join(tmpdir(), 'yarramate-likec4-project-'))
    const project = join(parent, 'governed-change')
    try {
      const result = runLikeC4Cli(
        [
          'export-project',
          'examples/governed-change/all.projection.yaml',
          'examples/governed-change/likec4.mapping.yaml',
          project,
          'examples/governed-change/yarramate.workspace.yaml',
        ],
        repositoryRoot,
      )

      expect(result).toEqual({
        exitCode: 0,
        stdout: `Wrote LikeC4 project to ${project}\n`,
        stderr: '',
      })
      expect(readFileSync(join(project, 'model.likec4'), 'utf8')).toContain(
        "controlPlane = applicationComponent 'Control plane'",
      )
      expect(
        JSON.parse(
          readFileSync(join(project, 'likec4.config.json'), 'utf8'),
        ),
      ).toMatchObject({
        name: 'yarramate-governed-change-1-0',
      })
      expect(
        readFileSync(join(project, 'specification.likec4'), 'utf8'),
      ).toContain('element driver')
      const marker = JSON.parse(
        readFileSync(
          join(project, 'yarramate.generated.json'),
          'utf8',
        ),
      )
      expect(marker).toEqual({
        format: 'yarramate/likec4-generated-project/v1',
        projection: 'governed-change@1.0',
        mapping: 'governed-change-likec4@1.0',
        files: [
          'likec4.config.json',
          'model.likec4',
          'specification.likec4',
        ],
      })
      const markerSchema = JSON.parse(
        readFileSync(
          join(
            repositoryRoot,
            'schema/yarramate-likec4-generated-project.schema.json',
          ),
          'utf8',
        ),
      )
      const validateMarker = new Ajv2020({ allErrors: true }).compile(
        markerSchema,
      )
      expect(
        validateMarker(marker),
        JSON.stringify(validateMarker.errors ?? []),
      ).toBe(true)

      const validation = spawnSync(
        join(repositoryRoot, 'node_modules/.bin/likec4'),
        ['validate', '--json', '--no-layout', project],
        { cwd: repositoryRoot, encoding: 'utf8' },
      )
      expect(
        validation.status,
        `${validation.stderr}\n${validation.stdout}`,
      ).toBe(0)
      expect(JSON.parse(validation.stdout)).toMatchObject({
        valid: true,
        errors: [],
      })
    } finally {
      rmSync(parent, { recursive: true, force: true })
    }
  })

  it('safely regenerates a project carrying its matching marker', () => {
    const parent = mkdtempSync(join(tmpdir(), 'yarramate-likec4-update-'))
    const project = join(parent, 'governed-change')
    const args = [
      'export-project',
      'examples/governed-change/all.projection.yaml',
      'examples/governed-change/likec4.mapping.yaml',
      project,
      'examples/governed-change/yarramate.workspace.yaml',
    ]
    try {
      expect(runLikeC4Cli(args, repositoryRoot).exitCode).toBe(0)
      writeFileSync(join(project, 'review-notes.md'), 'preserve me\n')

      const result = runLikeC4Cli(args, repositoryRoot)

      expect(result).toEqual({
        exitCode: 0,
        stdout: `Updated LikeC4 project at ${project}\n`,
        stderr: '',
      })
      expect(readFileSync(join(project, 'review-notes.md'), 'utf8')).toBe(
        'preserve me\n',
      )
    } finally {
      rmSync(parent, { recursive: true, force: true })
    }
  })

  it('refuses to overwrite an existing project directory', () => {
    const project = mkdtempSync(
      join(tmpdir(), 'yarramate-likec4-existing-'),
    )
    try {
      const result = runLikeC4Cli(
        [
          'export-project',
          'examples/governed-change/all.projection.yaml',
          'examples/governed-change/likec4.mapping.yaml',
          project,
          'examples/governed-change/yarramate.workspace.yaml',
        ],
        repositoryRoot,
      )

      expect(result).toEqual({
        exitCode: 2,
        stdout: '',
        stderr: `Output directory already exists: ${project}\n`,
      })
    } finally {
      rmSync(project, { recursive: true, force: true })
    }
  })
})
