import { describe, expect, it } from 'vitest'
import {
  compareArchitectureStates,
  compileWorkspace,
  evaluateProjection,
  type AdapterMapping,
  type ProjectionDefinition,
} from '../src/index.js'
import { exportLikeC4 } from '../src/adapters/likec4-export.js'
import type { LikeC4KindMapping } from '../src/adapters/likec4-kind-mapping.js'

const source = `format: yarramate/v1
id: payments
profile: yarramate/core@0.1
concepts:
  - id: checkout
    kind: applicationComponent
    name: Checkout
    description: Accepts customer orders
  - id: ledger
    kind: applicationComponent
    name: Ledger
relationships:
  - id: checkout-uses-ledger
    kind: serving
    from: ledger
    to: checkout
    name: serves
`

const projection: ProjectionDefinition = {
  format: 'yarramate/projection/v1',
  id: 'payments-context',
  version: '1.0',
  query: {},
  presentation: {
    title: 'Payments context',
    description: 'Applications participating in payment processing',
  },
}

const mapping: AdapterMapping = {
  format: 'yarramate/adapter-mapping/v1',
  id: 'payments-likec4',
  version: '1.0',
  adapter: 'likec4',
  mappings: [
    {
      native: 'payments#checkout',
      external: 'checkout',
      type: 'concept',
    },
    {
      native: 'payments#ledger',
      external: 'ledger',
      type: 'concept',
    },
  ],
}

describe('exportLikeC4', () => {
  it('renders a projection as deterministic LikeC4 model and view source', () => {
    const compilation = compileWorkspace([
      { path: 'payments.yaml', source },
    ])
    expect(compilation.ok).toBe(true)
    if (!compilation.ok) return

    const result = exportLikeC4(
      evaluateProjection(compilation.graph, projection),
      mapping,
    )

    expect(result).toEqual({
      ok: true,
      source: `// Generated by YarraMate. Edit the native documents, not this file.
model {
  checkout = applicationComponent 'Checkout' {
    description 'Accepts customer orders'
    metadata {
      yarramateId 'payments#checkout'
      yarramateKind 'yarramate/core@0.1#applicationComponent'
    }
  }
  ledger = applicationComponent 'Ledger' {
    metadata {
      yarramateId 'payments#ledger'
      yarramateKind 'yarramate/core@0.1#applicationComponent'
    }
  }

  ledger -[serving]-> checkout 'serves' {
    metadata {
      yarramateId 'payments#checkout-uses-ledger'
      yarramateKind 'yarramate/core@0.1#serving'
    }
  }
}

views {
  view payments-context {
    title 'Payments context'
    description 'Applications participating in payment processing'
    include *
    autoLayout LeftRight
  }
}
`,
    })
  })

  it('reports every projected concept without a LikeC4 identity', () => {
    const compilation = compileWorkspace([
      { path: 'payments.yaml', source },
    ])
    expect(compilation.ok).toBe(true)
    if (!compilation.ok) return

    const result = exportLikeC4(
      evaluateProjection(compilation.graph, projection),
      { ...mapping, mappings: mapping.mappings.slice(0, 1) },
    )

    expect(result).toEqual({
      ok: false,
      diagnostics: [
        {
          severity: 'error',
          code: 'YMLC102',
          message:
            'Projected concept "payments#ledger" has no LikeC4 mapping',
          subject: 'payments#ledger',
          path: 'payments.yaml',
          pointer: '/concepts/1/kind',
          line: 10,
          column: 11,
        },
      ],
    })
  })

  it('is independent of projection and mapping input order', () => {
    const compilation = compileWorkspace([
      { path: 'payments.yaml', source },
    ])
    expect(compilation.ok).toBe(true)
    if (!compilation.ok) return
    const selected = evaluateProjection(compilation.graph, projection)

    const first = exportLikeC4(selected, mapping)
    const second = exportLikeC4(
      {
        ...selected,
        subjects: [...selected.subjects].reverse(),
        claims: [...selected.claims].reverse(),
      },
      { ...mapping, mappings: [...mapping.mappings].reverse() },
    )

    expect(second).toEqual(first)
  })

  it('carries selected native claims as flat traceability metadata', () => {
    const compilation = compileWorkspace([
      {
        path: 'metadata.yaml',
        source: `format: yarramate/v1
id: metadata
profile: yarramate/core@0.1
concepts:
  - id: team
    kind: businessActor
    name: Platform team
  - id: residency
    kind: constraint
    name: Australia only
  - id: service
    kind: applicationComponent
    name: Payments service
    status: current
    owner: team
    constraints:
      - id: residency
        ref: residency
    references:
      - id: policy-source
        ref: residency
  - id: record
    kind: dataObject
    name: Payment record
relationships:
  - id: reads-record
    kind: access
    from: service
    to: record
    name: reads
    description: Reads the governed record without copying it
    mode: read
    references:
      - id: policy-source
        ref: residency
`,
      },
    ])
    expect(compilation.ok).toBe(true)
    if (!compilation.ok) return
    const result = exportLikeC4(
      evaluateProjection(compilation.graph, {
        ...projection,
        id: 'metadata',
      }),
      {
        ...mapping,
        mappings: [
          ['metadata#record', 'record'],
          ['metadata#residency', 'residency'],
          ['metadata#service', 'service'],
          ['metadata#team', 'team'],
        ].map(([native, external]) => ({
          native: native!,
          external: external!,
          type: 'concept' as const,
        })),
      },
    )

    expect(result.ok).toBe(true)
    if (!result.ok) return
    expect(result.source).toContain(`service = applicationComponent 'Payments service' {
    metadata {
      yarramateId 'metadata#service'
      yarramateKind 'yarramate/core@0.1#applicationComponent'
      status 'current'
      owner 'metadata#team'
      constraints ['metadata#residency']
      references ['metadata#residency']
    }
  }`)
    expect(result.source).toContain(`service -[access]-> record 'reads' {
    description 'Reads the governed record without copying it'
    metadata {
      yarramateId 'metadata#reads-record'
      yarramateKind 'yarramate/core@0.1#access'
      mode 'read'
      references ['metadata#residency']
    }
  }`)
  })

  it('applies explicit external kinds while preserving semantic kinds', () => {
    const compilation = compileWorkspace([
      { path: 'payments.yaml', source },
    ])
    expect(compilation.ok).toBe(true)
    if (!compilation.ok) return
    const kinds: LikeC4KindMapping = {
      format: 'yarramate/likec4-kind-mapping/v1',
      id: 'collapsed',
      version: '1.0',
      conceptKinds: [
        {
          native: 'yarramate/core@0.1#applicationComponent',
          external: 'element',
        },
      ],
      relationshipKinds: [
        {
          native: 'yarramate/core@0.1#serving',
          external: 'association',
        },
      ],
    }

    const result = exportLikeC4(
      evaluateProjection(compilation.graph, projection),
      mapping,
      kinds,
    )

    expect(result.ok).toBe(true)
    if (!result.ok) return
    expect(result.source).toContain(`checkout = element 'Checkout' {
    description 'Accepts customer orders'
    metadata {
      yarramateId 'payments#checkout'
      yarramateKind 'yarramate/core@0.1#applicationComponent'
    }
  }`)
    expect(result.source).toContain(
      `ledger -[association]-> checkout 'serves'`,
    )
    expect(result.source).toContain(
      `yarramateKind 'yarramate/core@0.1#serving'`,
    )
  })

  it('renders adapter-only comparison metadata and view styles', () => {
    const compilation = compileWorkspace([
      {
        path: 'payments.yaml',
        source: `format: yarramate/v1
id: payments
profile: yarramate/core@0.1
states:
  - id: baseline
    kind: baseline
    name: Baseline
  - id: target
    kind: target
    name: Target
concepts:
  - id: checkout
    kind: applicationComponent
    name: Checkout
  - id: ledger
    kind: applicationComponent
    name: Ledger
    presentIn: [baseline]
  - id: platform
    kind: applicationComponent
    name: Platform
    presentIn: [target]
relationships: []
`,
      },
    ])
    expect(compilation.ok).toBe(true)
    if (!compilation.ok) return
    const comparison = compareArchitectureStates(
      compilation.graph,
      'payments#baseline',
      'payments#target',
    )
    expect(comparison.ok).toBe(true)
    if (!comparison.ok) return

    const result = exportLikeC4(
      evaluateProjection(compilation.graph, {
        ...projection,
        query: {
          states: ['payments#baseline', 'payments#target'],
        },
      }),
      {
        ...mapping,
        mappings: [
          ...mapping.mappings,
          {
            native: 'payments#platform',
            external: 'platform',
            type: 'concept',
          },
        ],
      },
      undefined,
      { comparison: comparison.comparison },
    )

    expect(result.ok).toBe(true)
    if (!result.ok) return
    expect(result.source).toContain(`yarramateChange 'retained'`)
    expect(result.source).toContain(`yarramateChange 'removed'`)
    expect(result.source).toContain(`yarramateChange 'added'`)
    expect(result.source).toContain(
      `style platform { color green }`,
    )
    expect(result.source).toContain(
      `style ledger { color red; border dashed }`,
    )
    expect(result.source).toContain(
      `style checkout { color gray }`,
    )
  })

  it('maps supported presentation direction without changing projected members', () => {
    const compilation = compileWorkspace([{ path: 'payments.yaml', source }])
    expect(compilation.ok).toBe(true)
    if (!compilation.ok) return
    const result = exportLikeC4(
      evaluateProjection(compilation.graph, {
        ...projection,
        presentation: {
          ...projection.presentation,
          direction: 'top-down',
        },
      }),
      mapping,
    )

    expect(result.ok).toBe(true)
    if (!result.ok) return
    expect(result.source).toContain('autoLayout TopBottom')
    expect(result.source).toContain('checkout = applicationComponent')
    expect(result.source).toContain('ledger = applicationComponent')
  })
})
