#!/usr/bin/env node
// Two package assets as TypeScript modules, so the path-free entries can
// carry them without a filesystem (ADR 0156): the shipped question
// catalogue (`catalogues/core-enrichment.yaml`, which `design`, `ask` and
// the editor all evaluate) and the LikeC4 specification
// (`assets/likec4/specification.likec4`, which every generated project
// ships beside its model). The files stay where they are and stay the
// source of truth; `test/generated-assets.test.ts` fails when a committed
// module is not what regenerating produces, the same guard the validators
// have.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const root = new URL('..', import.meta.url)
const read = (relative) => readFileSync(new URL(relative, root), 'utf8')

const banner = (source, constant) =>
  `// GENERATED by scripts/generate-assets.mjs from ${source}. Do not edit;\n` +
  `// run \`pnpm generate:assets\` and commit the result.\n` +
  `export const ${constant} = ${JSON.stringify(read(source))}\n`

export const generateShippedCatalogue = () =>
  banner('catalogues/core-enrichment.yaml', 'SHIPPED_CATALOGUE_SOURCE')

export const generateLikeC4Specification = () =>
  banner('assets/likec4/specification.likec4', 'LIKEC4_SPECIFICATION_SOURCE')

export const OUTPUTS = [
  ['src/shipped-catalogue.generated.ts', generateShippedCatalogue],
  ['src/likec4-specification.generated.ts', generateLikeC4Specification],
]

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  for (const [relative, generate] of OUTPUTS) {
    writeFileSync(new URL(relative, root), generate(), 'utf8')
    process.stdout.write(`wrote ${relative}\n`)
  }
}
