import type { ValidateFunction } from 'ajv'
import * as generatedOperations from './schema-validators-operations.generated.js'
import * as generated from './schema-validators.generated.js'

/**
 * The package's JSON Schema validators, precompiled at BUILD time.
 *
 * Ajv normally compiles a schema by generating source and calling
 * `new Function`, and where that happens decided two releases:
 *
 * - Cloudflare's `workerd` **permits** code generation during module
 *   evaluation and **forbids** it at request time. 1.15.2 deferred compilation
 *   to first use to save startup CPU, which put it inside a request, and every
 *   request that validated anything threw `EvalError`.
 * - 1.15.3 moved compilation back to import, where it is allowed, but that
 *   only avoids the forbidden context. The codegen still ran, and Workers
 *   budget startup CPU separately (400ms) and refuse a Worker that exceeds it.
 *   An adopter's deploy came back at 439ms against that line.
 *
 * Precompiling removes the question instead of answering it: there is no
 * compile step left to put in the wrong place, and no amount of future
 * refactoring can move one back. `schema-validators.generated.js` is committed
 * and regenerated by `pnpm generate:validators`;
 * `test/generated-validators.test.ts` regenerates and compares byte for byte,
 * so a schema edited without regenerating fails there rather than shipping a
 * validator that checks the old shape.
 *
 * Behaviour is unchanged: same `allErrors` collection, same messages, same
 * `errors` property on each validator. `validateOperations` is emitted from an
 * instance with `discriminator` enabled, which is compiled into it.
 *
 * Ajv's COMPILER is a build dependency now rather than a runtime one. Two pure
 * helpers - a deep-equal and a UCS-2 string length - are still imported from
 * `ajv/dist/runtime` by the generated module, which is the accurate claim.
 */
export const validateDocument = generated.validateDocument as ValidateFunction
export const validateProfile = generated.validateProfile as ValidateFunction
export const validatePattern = generated.validatePattern as ValidateFunction
export const validateWorkspace = generated.validateWorkspace as ValidateFunction
export const validateProjection =
  generated.validateProjection as ValidateFunction
export const validateEvidence = generated.validateEvidence as ValidateFunction
export const validateCoreContract =
  generated.validateCoreContract as ValidateFunction
export const validateAdapterMapping =
  generated.validateAdapterMapping as ValidateFunction
export const validateCatalogue = generated.validateCatalogue as ValidateFunction
export const validateOperations =
  generatedOperations.validateOperations as ValidateFunction
